import { useState, useRef } from "react";
import QRCode from "react-qr-code";
import { motion, AnimatePresence } from "framer-motion";
import "./QRGenerator.css";
import { qrTypes } from "./qrUtils";

export default function QRGenerator() {
  const [qrType, setQrType] = useState("url");
  const [value, setValue] = useState("");
  const [ssid, setSsid] = useState("");
  const [password, setPassword] = useState("");
  const [email, setEmail] = useState("");
  
  // Customization state
  const [fgColor, setFgColor] = useState("#000000");
  const [bgColor, setBgColor] = useState("#ffffff");
  const [qrSize, setQrSize] = useState(280);
  const [margin, setMargin] = useState(10);
  const [errorLevel, setErrorLevel] = useState("H");
  
  const qrRef = useRef();
  const fileInputRef = useRef();

  // Templates
  const templates = {
    classic: { fg: "#000000", bg: "#ffffff" },
    neon: { fg: "#00ff00", bg: "#000000" },
    dark: { fg: "#ffffff", bg: "#1a1a1a" },
    glass: { fg: "#2563eb", bg: "#f0f9ff" },
    gradient: { fg: "#5b7cff", bg: "#0a0e27" },
    business: { fg: "#1e40af", bg: "#f8fafc" },
    whatsapp: { fg: "#25d366", bg: "#ffffff" },
    instagram: { fg: "#e1306c", bg: "#feda75" },
  };

  // Generate QR value based on type
  const generateQRValue = () => {
    switch (qrType) {
      case "url":
        return value.trim() ? (value.startsWith("http") ? value : `https://${value}`) : "";
      case "text":
        return value;
      case "email":
        return email.trim() ? `mailto:${email}` : "";
      case "phone":
        return value.trim() ? `tel:${value}` : "";
      case "wifi":
        return ssid.trim() && password.trim() 
          ? `WIFI:T:WPA;S:${ssid};P:${password};;` 
          : "";
      default:
        return value;
    }
  };

  const qrValue = generateQRValue();

  // Download QR Code
  const downloadQR = (format) => {
    const svg = qrRef.current?.querySelector("svg");
    if (!svg) return;

    const canvas = document.createElement("canvas");
    const size = qrSize + margin * 2;
    canvas.width = size;
    canvas.height = size;
    
    const ctx = canvas.getContext("2d");
    ctx.fillStyle = bgColor;
    ctx.fillRect(0, 0, size, size);

    const svgString = new XMLSerializer().serializeToString(svg);
    const img = new Image();
    img.onload = () => {
      ctx.drawImage(img, margin, margin, qrSize, qrSize);
      if (format === "png") {
        canvas.toBlob((blob) => {
          const url = URL.createObjectURL(blob);
          const a = document.createElement("a");
          a.href = url;
          a.download = "qr-code.png";
          a.click();
        });
      } else if (format === "svg") {
        const link = document.createElement("a");
        link.href = `data:image/svg+xml;base64,${btoa(svgString)}`;
        link.download = "qr-code.svg";
        link.click();
      }
    };
    img.src = `data:image/svg+xml;base64,${btoa(svgString)}`;
  };

  // Copy QR to clipboard
  const copyQR = async () => {
    const svg = qrRef.current?.querySelector("svg");
    if (!svg) return;

    try {
      const canvas = document.createElement("canvas");
      const size = qrSize + margin * 2;
      canvas.width = size;
      canvas.height = size;
      const ctx = canvas.getContext("2d");
      ctx.fillStyle = bgColor;
      ctx.fillRect(0, 0, size, size);

      const svgString = new XMLSerializer().serializeToString(svg);
      const img = new Image();
      img.onload = async () => {
        ctx.drawImage(img, margin, margin, qrSize, qrSize);
        canvas.toBlob(async (blob) => {
          await navigator.clipboard.write([
            new ClipboardItem({ "image/png": blob })
          ]);
          alert("QR Code copied to clipboard!");
        });
      };
      img.src = `data:image/svg+xml;base64,${btoa(svgString)}`;
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  // Share QR
  const shareQR = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: "QR Code",
          text: "Check out this QR code generated by Zentra AI!",
          url: window.location.href,
        });
      } catch (err) {
        console.log("Share cancelled");
      }
    }
  };

  // Reset
  const resetQR = () => {
    setValue("");
    setSsid("");
    setPassword("");
    setEmail("");
    setFgColor("#000000");
    setBgColor("#ffffff");
    setQrSize(280);
    setMargin(10);
  };

  // Handle logo upload
  const handleLogoUpload = (e) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        console.log("Logo uploaded");
      };
      reader.readAsDataURL(file);
    }
  };

  // Paste from clipboard
  const pasteFromClipboard = async () => {
    try {
      const text = await navigator.clipboard.readText();
      setValue(text);
    } catch {
      alert("Failed to read clipboard");
    }
  };

  // Clear input
  const clearInput = () => {
    if (qrType === "wifi") {
      setSsid("");
      setPassword("");
    } else if (qrType === "email") {
      setEmail("");
    } else {
      setValue("");
    }
  };

  return (
    <div className="qr-generator-wrapper">
      {/* Animated Background Elements */}
      <div className="aurora-bg"></div>
      <div className="mesh-gradient"></div>
      
      {/* Floating Orbs */}
      <motion.div className="orb orb-1" animate={{ y: [0, -30, 0], x: [0, 15, 0] }} transition={{ duration: 8, repeat: Infinity }} />
      <motion.div className="orb orb-2" animate={{ y: [0, 30, 0], x: [0, -15, 0] }} transition={{ duration: 10, repeat: Infinity, delay: 1 }} />
      <motion.div className="orb orb-3" animate={{ y: [0, -20, 0], x: [0, 10, 0] }} transition={{ duration: 12, repeat: Infinity, delay: 2 }} />

      <div className="qr-container">
        {/* Hero Section */}
        <motion.div
          className="hero-section"
          initial={{ opacity: 0, y: -30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <h1>QR Code Generator</h1>
          <p>Generate beautiful, customizable QR codes instantly with AI-powered design</p>
        </motion.div>

        {/* Main Content Grid */}
        <div className="content-wrapper">
          {/* Left Column - Input Section */}
          <motion.div
            className="input-column"
            initial={{ opacity: 0, x: -30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
          >
            {/* QR Type Tabs */}
            <div className="tabs-container">
              <div className="tabs-grid">
                {qrTypes.map((type, idx) => (
                  <motion.button
                    key={type.id}
                    className={`tab-button ${qrType === type.id ? "active" : ""}`}
                    onClick={() => setQrType(type.id)}
                    whileHover={{ scale: 1.08 }}
                    whileTap={{ scale: 0.95 }}
                    transition={{ type: "spring", stiffness: 300 }}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: idx * 0.05 }}
                  >
                    <span className="tab-icon">{type.icon}</span>
                    <span className="tab-label">{type.title}</span>
                  </motion.button>
                ))}
              </div>
            </div>

            {/* Input Card */}
            <motion.div
              className="input-card"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.3 }}
            >
              <div className="input-header">
                <span className="input-title">
                  {qrTypes.find(t => t.id === qrType)?.icon} {qrTypes.find(t => t.id === qrType)?.title}
                </span>
              </div>

              <AnimatePresence mode="wait">
                <motion.div
                  key={qrType}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  transition={{ duration: 0.3 }}
                  className="input-body"
                >
                  {qrType === "url" && (
                    <input
                      type="text"
                      placeholder="https://example.com"
                      value={value}
                      onChange={(e) => setValue(e.target.value)}
                      className="input-field"
                    />
                  )}

                  {qrType === "text" && (
                    <textarea
                      placeholder="Enter your text (max 2953 characters)"
                      value={value}
                      onChange={(e) => setValue(e.target.value)}
                      className="input-field textarea"
                      rows={4}
                    />
                  )}

                  {qrType === "email" && (
                    <input
                      type="email"
                      placeholder="user@example.com"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      className="input-field"
                    />
                  )}

                  {qrType === "phone" && (
                    <input
                      type="tel"
                      placeholder="+1 (555) 000-0000"
                      value={value}
                      onChange={(e) => setValue(e.target.value)}
                      className="input-field"
                    />
                  )}

                  {qrType === "wifi" && (
                    <div className="wifi-inputs">
                      <input
                        type="text"
                        placeholder="Network SSID"
                        value={ssid}
                        onChange={(e) => setSsid(e.target.value)}
                        className="input-field"
                      />
                      <input
                        type="password"
                        placeholder="Password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        className="input-field"
                      />
                    </div>
                  )}
                </motion.div>
              </AnimatePresence>

              <div className="input-actions">
                <motion.button
                  className="action-icon-btn"
                  onClick={pasteFromClipboard}
                  whileHover={{ scale: 1.15 }}
                  whileTap={{ scale: 0.9 }}
                  title="Paste from clipboard"
                >
                  📋
                </motion.button>
                <motion.button
                  className="action-icon-btn"
                  onClick={clearInput}
                  whileHover={{ scale: 1.15 }}
                  whileTap={{ scale: 0.9 }}
                  title="Clear input"
                >
                  ✕
                </motion.button>
              </div>
            </motion.div>

            {/* Customization Section */}
            <motion.div
              className="customization-card"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.4 }}
            >
              <h3 className="card-title">Customization</h3>

              {/* Templates */}
              <div className="setting-group">
                <label className="setting-label">Templates</label>
                <div className="template-grid">
                  {Object.entries(templates).map(([name, colors]) => (
                    <motion.button
                      key={name}
                      className={`template-item ${name}`}
                      onClick={() => {
                        setFgColor(colors.fg);
                        setBgColor(colors.bg);
                      }}
                      whileHover={{ scale: 1.08 }}
                      whileTap={{ scale: 0.95 }}
                      title={name}
                    >
                      <div
                        className="template-preview"
                        style={{
                          background: colors.bg,
                          borderColor: colors.fg,
                        }}
                      />
                    </motion.button>
                  ))}
                </div>
              </div>

              {/* Color Pickers */}
              <div className="setting-group">
                <label className="setting-label">Colors</label>
                <div className="colors-row">
                  <div className="color-picker-item">
                    <label className="color-label">Foreground</label>
                    <input
                      type="color"
                      value={fgColor}
                      onChange={(e) => setFgColor(e.target.value)}
                      className="color-picker"
                    />
                    <span className="color-value">{fgColor}</span>
                  </div>
                  <div className="color-picker-item">
                    <label className="color-label">Background</label>
                    <input
                      type="color"
                      value={bgColor}
                      onChange={(e) => setBgColor(e.target.value)}
                      className="color-picker"
                    />
                    <span className="color-value">{bgColor}</span>
                  </div>
                </div>
              </div>

              {/* Size Sliders */}
              <div className="setting-group">
                <label className="setting-label">Size: {qrSize}px</label>
                <input
                  type="range"
                  min="150"
                  max="400"
                  value={qrSize}
                  onChange={(e) => setQrSize(Number(e.target.value))}
                  className="slider"
                />
              </div>

              <div className="setting-group">
                <label className="setting-label">Margin: {margin}px</label>
                <input
                  type="range"
                  min="0"
                  max="50"
                  value={margin}
                  onChange={(e) => setMargin(Number(e.target.value))}
                  className="slider"
                />
              </div>

              {/* Error Correction */}
              <div className="setting-group">
                <label className="setting-label">Error Correction</label>
                <select
                  value={errorLevel}
                  onChange={(e) => setErrorLevel(e.target.value)}
                  className="select-input"
                >
                  <option value="L">Low (7%)</option>
                  <option value="M">Medium (15%)</option>
                  <option value="Q">Quartile (25%)</option>
                  <option value="H">High (30%)</option>
                </select>
              </div>

              {/* Logo Upload */}
              <div className="setting-group">
                <label className="setting-label">Logo</label>
                <motion.button
                  className="upload-btn"
                  onClick={() => fileInputRef.current?.click()}
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                >
                  📷 Upload Logo
                </motion.button>
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/*"
                  onChange={handleLogoUpload}
                  style={{ display: "none" }}
                />
              </div>
            </motion.div>
          </motion.div>

          {/* Right Column - Preview Section */}
          <motion.div
            className="preview-column"
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
          >
            {/* QR Preview Card */}
            <motion.div
              className="qr-preview-card"
              animate={{ y: [0, -8, 0] }}
              transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
            >
              <div className="qr-display" ref={qrRef}>
                {qrValue ? (
                  <motion.div
                    key={qrValue}
                    initial={{ opacity: 0, scale: 0.8 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.4 }}
                  >
                    <QRCode
                      value={qrValue}
                      size={qrSize}
                      fgColor={fgColor}
                      bgColor={bgColor}
                      level={errorLevel}
                      includeMargin={true}
                    />
                  </motion.div>
                ) : (
                  <div className="empty-state">
                    <motion.div
                      className="empty-icon"
                      animate={{ scale: [1, 1.1, 1], rotate: [0, 5, -5, 0] }}
                      transition={{ duration: 3, repeat: Infinity }}
                    >
                      ⚡
                    </motion.div>
                    <p className="empty-text">Enter content to generate</p>
                  </div>
                )}
              </div>
              <div className="watermark">Zentra AI QR Generator 🇮🇳</div>
            </motion.div>

            {/* Action Buttons */}
            <motion.div
              className="action-buttons"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.5 }}
            >
              <motion.button
                className="btn btn-primary"
                onClick={() => downloadQR("png")}
                disabled={!qrValue}
                whileHover={qrValue ? { scale: 1.05, y: -2 } : {}}
                whileTap={qrValue ? { scale: 0.95 } : {}}
              >
                <span>📥</span> PNG
              </motion.button>
              <motion.button
                className="btn btn-primary"
                onClick={() => downloadQR("svg")}
                disabled={!qrValue}
                whileHover={qrValue ? { scale: 1.05, y: -2 } : {}}
                whileTap={qrValue ? { scale: 0.95 } : {}}
              >
                <span>📤</span> SVG
              </motion.button>
              <motion.button
                className="btn btn-secondary"
                onClick={copyQR}
                disabled={!qrValue}
                whileHover={qrValue ? { scale: 1.05, y: -2 } : {}}
                whileTap={qrValue ? { scale: 0.95 } : {}}
              >
                <span>📋</span> Copy
              </motion.button>
              <motion.button
                className="btn btn-secondary"
                onClick={shareQR}
                disabled={!qrValue}
                whileHover={qrValue ? { scale: 1.05, y: -2 } : {}}
                whileTap={qrValue ? { scale: 0.95 } : {}}
              >
                <span>🔗</span> Share
              </motion.button>
              <motion.button
                className="btn btn-reset"
                onClick={resetQR}
                whileHover={{ scale: 1.05, y: -2 }}
                whileTap={{ scale: 0.95 }}
              >
                <span>🔄</span> Reset
              </motion.button>
            </motion.div>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
