import { useState, useRef } from "react";
import QRCode from "react-qr-code";
import { motion, AnimatePresence } from "framer-motion";
import "./QRGenerator.css";
import { qrTypes } from "./qrUtils";

export default function QRGenerator() {
  const [qrType, setQrType] = useState("url");
  const [value, setValue] = useState("");
  const [ssid, setSsid] = useState("");
  const [password, setPassword] = useState("");
  const [email, setEmail] = useState("");
  
  // Customization state
  const [fgColor, setFgColor] = useState("#000000");
  const [bgColor, setBgColor] = useState("#ffffff");
  const [qrSize, setQrSize] = useState(250);
  const [margin, setMargin] = useState(10);
  const [errorLevel, setErrorLevel] = useState("H");
  const [roundedQR, setRoundedQR] = useState(false);
  const [template, setTemplate] = useState("classic");
  const [logoPreview, setLogoPreview] = useState(null);
  const qrRef = useRef();
  const fileInputRef = useRef();

  // Apply template styles
  const templates = {
    classic: { fg: "#000000", bg: "#ffffff" },
    neon: { fg: "#00ff00", bg: "#000000" },
    dark: { fg: "#ffffff", bg: "#1a1a1a" },
    glass: { fg: "#2563eb", bg: "#f0f9ff" },
    gradient: { fg: "#5b7cff", bg: "#0a0e27" },
    business: { fg: "#1e40af", bg: "#f8fafc" },
    whatsapp: { fg: "#25d366", bg: "#ffffff" },
    instagram: { fg: "#e1306c", bg: "#feda75" },
  };

  // Generate QR value based on type
  const generateQRValue = () => {
    switch (qrType) {
      case "url":
        return value.trim() ? (value.startsWith("http") ? value : `https://${value}`) : "";
      case "text":
        return value;
      case "email":
        return email.trim() ? `mailto:${email}` : "";
      case "phone":
        return value.trim() ? `tel:${value}` : "";
      case "wifi":
        return ssid.trim() && password.trim() 
          ? `WIFI:T:WPA;S:${ssid};P:${password};;` 
          : "";
      default:
        return value;
    }
  };

  const qrValue = generateQRValue();

  // Download QR Code
  const downloadQR = (format) => {
    const svg = qrRef.current?.querySelector("svg");
    if (!svg) return;

    const canvas = document.createElement("canvas");
    const size = qrSize + margin * 2;
    canvas.width = size;
    canvas.height = size;
    
    const ctx = canvas.getContext("2d");
    ctx.fillStyle = bgColor;
    ctx.fillRect(0, 0, size, size);

    const svgString = new XMLSerializer().serializeToString(svg);
    const img = new Image();
    img.onload = () => {
      ctx.drawImage(img, margin, margin, qrSize, qrSize);
      if (format === "png") {
        canvas.toBlob((blob) => {
          const url = URL.createObjectURL(blob);
          const a = document.createElement("a");
          a.href = url;
          a.download = "qr-code.png";
          a.click();
        });
      } else if (format === "svg") {
        const link = document.createElement("a");
        link.href = `data:image/svg+xml;base64,${btoa(svgString)}`;
        link.download = "qr-code.svg";
        link.click();
      }
    };
    img.src = `data:image/svg+xml;base64,${btoa(svgString)}`;
  };

  // Copy QR to clipboard
  const copyQR = async () => {
    const svg = qrRef.current?.querySelector("svg");
    if (!svg) return;

    try {
      const canvas = document.createElement("canvas");
      const size = qrSize + margin * 2;
      canvas.width = size;
      canvas.height = size;
      const ctx = canvas.getContext("2d");
      ctx.fillStyle = bgColor;
      ctx.fillRect(0, 0, size, size);

      const svgString = new XMLSerializer().serializeToString(svg);
      const img = new Image();
      img.onload = async () => {
        ctx.drawImage(img, margin, margin, qrSize, qrSize);
        canvas.toBlob(async (blob) => {
          await navigator.clipboard.write([
            new ClipboardItem({ "image/png": blob })
          ]);
          alert("QR Code copied to clipboard!");
        });
      };
      img.src = `data:image/svg+xml;base64,${btoa(svgString)}`;
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  // Share QR
  const shareQR = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: "QR Code",
          text: "Check out this QR code generated by Zentra AI!",
          url: window.location.href,
        });
      } catch (err) {
        console.log("Share cancelled");
      }
    }
  };

  // Reset
  const resetQR = () => {
    setValue("");
    setSsid("");
    setPassword("");
    setEmail("");
    setFgColor("#000000");
    setBgColor("#ffffff");
    setQrSize(250);
    setMargin(10);
    setTemplate("classic");
    setLogoPreview(null);
  };

  // Handle logo upload
  const handleLogoUpload = (e) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        setLogoPreview(event.target?.result);
      };
      reader.readAsDataURL(file);
    }
  };

  // Paste from clipboard
  const pasteFromClipboard = async () => {
    try {
      const text = await navigator.clipboard.readText();
      setValue(text);
    } catch {
      alert("Failed to read clipboard");
    }
  };

  // Clear input
  const clearInput = () => {
    if (qrType === "wifi") {
      setSsid("");
      setPassword("");
    } else if (qrType === "email") {
      setEmail("");
    } else {
      setValue("");
    }
  };

  return (
    <div className="qr-generator">
      {/* Aurora Background */}
      <div className="aurora-bg">
        <div className="aurora aurora-1"></div>
        <div className="aurora aurora-2"></div>
        <div className="aurora aurora-3"></div>
      </div>

      {/* Mesh Gradient */}
      <div className="mesh-gradient"></div>

      {/* Floating Particles */}
      <div className="particles">
        {[...Array(20)].map((_, i) => (
          <motion.div
            key={i}
            className="particle"
            animate={{
              y: [0, -20, 0],
              x: [0, 10, 0],
              opacity: [0.3, 0.6, 0.3],
            }}
            transition={{
              duration: 3 + i * 0.2,
              repeat: Infinity,
              delay: i * 0.1,
            }}
          />
        ))}
      </div>

      <div className="qr-container">
        {/* Hero Section */}
        <motion.div
          className="hero-section"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <h1>QR Code Generator</h1>
          <p>Generate beautiful QR Codes instantly with AI-powered customization.</p>
        </motion.div>

        {/* Tabs Section */}
        <motion.div
          className="tabs-wrapper"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.1 }}
        >
          <div className="premium-tabs">
            {qrTypes.map((type) => (
              <motion.button
                key={type.id}
                className={`tab-pill ${qrType === type.id ? "active" : ""}`}
                onClick={() => setQrType(type.id)}
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                layout
              >
                <span className="tab-icon">{type.icon}</span>
                <span className="tab-title">{type.title}</span>
                {qrType === type.id && (
                  <motion.div
                    className="tab-indicator"
                    layoutId="indicator"
                    transition={{ type: "spring", stiffness: 200, damping: 30 }}
                  />
                )}
              </motion.button>
            ))}
          </div>
        </motion.div>

        <div className="content-grid">
          {/* Left Column - Input & Preview */}
          <div className="left-column">
            {/* Premium Input Section */}
            <motion.div
              className="input-section"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.2 }}
            >
              <div className="glass-input-wrapper">
                <div className="input-icon">
                  {qrTypes.find(t => t.id === qrType)?.icon}
                </div>

                <AnimatePresence mode="wait">
                  <motion.div
                    key={qrType}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 0.3 }}
                    className="input-fields"
                  >
                    {qrType === "url" && (
                      <input
                        type="text"
                        placeholder="https://example.com"
                        value={value}
                        onChange={(e) => setValue(e.target.value)}
                        className="glass-input"
                      />
                    )}

                    {qrType === "text" && (
                      <textarea
                        placeholder="Enter your text"
                        value={value}
                        onChange={(e) => setValue(e.target.value)}
                        className="glass-input"
                        rows={3}
                      />
                    )}

                    {qrType === "email" && (
                      <input
                        type="email"
                        placeholder="user@example.com"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        className="glass-input"
                      />
                    )}

                    {qrType === "phone" && (
                      <input
                        type="tel"
                        placeholder="+91 9876543210"
                        value={value}
                        onChange={(e) => setValue(e.target.value)}
                        className="glass-input"
                      />
                    )}

                    {qrType === "wifi" && (
                      <>
                        <input
                          type="text"
                          placeholder="Network SSID"
                          value={ssid}
                          onChange={(e) => setSsid(e.target.value)}
                          className="glass-input"
                        />
                        <input
                          type="password"
                          placeholder="Password"
                          value={password}
                          onChange={(e) => setPassword(e.target.value)}
                          className="glass-input"
                        />
                      </>
                    )}
                  </motion.div>
                </AnimatePresence>

                <div className="input-actions">
                  <motion.button
                    className="action-btn"
                    onClick={pasteFromClipboard}
                    whileHover={{ scale: 1.1 }}
                    whileTap={{ scale: 0.9 }}
                    title="Paste from clipboard"
                  >
                    📋
                  </motion.button>
                  <motion.button
                    className="action-btn"
                    onClick={clearInput}
                    whileHover={{ scale: 1.1 }}
                    whileTap={{ scale: 0.9 }}
                    title="Clear input"
                  >
                    ✕
                  </motion.button>
                </div>
              </div>
            </motion.div>

            {/* QR Preview Card */}
            <motion.div
              className="qr-card-wrapper"
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.8, delay: 0.3 }}
            >
              <motion.div
                className="qr-card"
                animate={{ y: [0, -10, 0] }}
                transition={{ duration: 3, repeat: Infinity }}
              >
                <div className="qr-display" ref={qrRef}>
                  {qrValue ? (
                    <QRCode
                      value={qrValue}
                      size={qrSize}
                      fgColor={fgColor}
                      bgColor={bgColor}
                      level={errorLevel}
                      includeMargin={true}
                    />
                  ) : (
                    <div className="empty-state">
                      <motion.div
                        animate={{ scale: [1, 1.1, 1] }}
                        transition={{ duration: 2, repeat: Infinity }}
                      >
                        ⚡
                      </motion.div>
                      <p>Enter something to generate QR</p>
                    </div>
                  )}
                </div>
              </motion.div>

              <div className="watermark">Made by Zentra AI 🇮🇳</div>

              {/* Action Buttons */}
              <motion.div
                className="action-buttons"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.4 }}
              >
                <motion.button
                  className="btn btn-primary"
                  onClick={() => downloadQR("png")}
                  disabled={!qrValue}
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                >
                  📥 PNG
                </motion.button>
                <motion.button
                  className="btn btn-primary"
                  onClick={() => downloadQR("svg")}
                  disabled={!qrValue}
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                >
                  📤 SVG
                </motion.button>
                <motion.button
                  className="btn btn-secondary"
                  onClick={copyQR}
                  disabled={!qrValue}
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                >
                  📋 Copy
                </motion.button>
                <motion.button
                  className="btn btn-secondary"
                  onClick={shareQR}
                  disabled={!qrValue}
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                >
                  🔗 Share
                </motion.button>
                <motion.button
                  className="btn btn-reset"
                  onClick={resetQR}
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                >
                  🔄 Reset
                </motion.button>
              </motion.div>
            </motion.div>
          </div>

          {/* Right Column - Customization */}
          <motion.div
            className="right-column customization-panel"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8, delay: 0.3 }}
          >
            <h2>Customization</h2>

            {/* Templates */}
            <div className="setting-group">
              <label>Templates</label>
              <div className="template-grid">
                {Object.entries(templates).map(([name, colors]) => (
                  <motion.button
                    key={name}
                    className={`template-btn ${template === name ? "active" : ""}`}
                    onClick={() => {
                      setTemplate(name);
                      setFgColor(colors.fg);
                      setBgColor(colors.bg);
                    }}
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    title={name}
                  >
                    <div
                      className="template-preview"
                      style={{
                        background: colors.bg,
                        borderColor: colors.fg,
                      }}
                    />
                    <span>{name}</span>
                  </motion.button>
                ))}
              </div>
            </div>

            {/* Color Pickers */}
            <div className="setting-group">
              <label>Foreground Color</label>
              <div className="color-input-wrapper">
                <input
                  type="color"
                  value={fgColor}
                  onChange={(e) => setFgColor(e.target.value)}
                  className="color-picker"
                />
                <span className="color-value">{fgColor}</span>
              </div>
            </div>

            <div className="setting-group">
              <label>Background Color</label>
              <div className="color-input-wrapper">
                <input
                  type="color"
                  value={bgColor}
                  onChange={(e) => setBgColor(e.target.value)}
                  className="color-picker"
                />
                <span className="color-value">{bgColor}</span>
              </div>
            </div>

            {/* Sliders */}
            <div className="setting-group">
              <label>QR Size ({qrSize}px)</label>
              <input
                type="range"
                min="150"
                max="400"
                value={qrSize}
                onChange={(e) => setQrSize(Number(e.target.value))}
                className="slider"
              />
            </div>

            <div className="setting-group">
              <label>Margin ({margin}px)</label>
              <input
                type="range"
                min="0"
                max="50"
                value={margin}
                onChange={(e) => setMargin(Number(e.target.value))}
                className="slider"
              />
            </div>

            {/* Error Correction */}
            <div className="setting-group">
              <label>Error Correction</label>
              <select
                value={errorLevel}
                onChange={(e) => setErrorLevel(e.target.value)}
                className="select-input"
              >
                <option value="L">Low (7%)</option>
                <option value="M">Medium (15%)</option>
                <option value="Q">Quartile (25%)</option>
                <option value="H">High (30%)</option>
              </select>
            </div>

            {/* Options */}
            <div className="setting-group">
              <label className="checkbox-label">
                <input
                  type="checkbox"
                  checked={roundedQR}
                  onChange={(e) => setRoundedQR(e.target.checked)}
                />
                <span>Rounded QR</span>
              </label>
            </div>

            {/* Logo Upload */}
            <div className="setting-group">
              <label>Logo</label>
              <motion.button
                className="btn btn-secondary full-width"
                onClick={() => fileInputRef.current?.click()}
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
              >
                📷 Upload Logo
              </motion.button>
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                onChange={handleLogoUpload}
                style={{ display: "none" }}
              />
              {logoPreview && (
                <motion.button
                  className="btn btn-reset full-width"
                  onClick={() => setLogoPreview(null)}
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                >
                  ✕ Remove Logo
                </motion.button>
              )}
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
